backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "static/images/uploads"  # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "site/content/_index.md"
        fields:
          - {label: Image, name: image, widget: image, required: false}
          - {label: "Homepage text", name: indexText, widget: markdown}
      - label: "Community Administrators"
        name: "communityAdministrators"
        file: "site/content/whoWeAre/communityAdministrators.md"
        fields:
          - label: Community Administrators
            name: individuals
            widget: list
            fields:
              - {label: Name, name: name, widget: markdown}
              - {label: Position, name: position, widget: string, required: false}
              - {label: Institution, name: institution, widget: string, required: false}
              - {label: Contact, name: contact, widget: string, required: false}
      - label: "Initiatives"
        name: "initiatives"
        file: "site/content/initiatives/index.md"
        fields:
          - label: Initiatives
            name: initiatives
            widget: list
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Title, name: title, widget: markdown, required: true}
              - {label: Date and Time, name: dateTime, widget: string, required: false}
              - {label: Description, name: description, widget: markdown, required: false}
              - {label: Location, name: location, widget: markdown, required: false}
              - {label: Who, name: who, widget: string, required: false}
              - {label: Registration Link, name: registrationLink, widget: markdown, required: false}
              - {label: Recordings, name: recordings, widget: markdown, required: false}         